apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app
  namespace: test-gitops
spec:
  destination:
    namespace: test-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook 
    repoURL: https://github.com/rishabhsvats/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
