apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: test-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: simple-app/app 
    repoURL: https://github.com/rishabhsvats/gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
