kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: pricelist
  namespace: pricelist
spec:
  scaleTargetRef:
    kind: Deployment
    name: pricelist
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
