
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bgd
  name: bgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      labels:
        app: bgd
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        resources:
          limits:
            memory: 2000Mi
            cpu: 2000m
          requests:
          
            cpu: 1000m
            memory: 1024Mi
        name: bgd
        env:
        - name: COLOR
          value: "blue"
      nodeSelector:
        topology.kubernetes.io/region: testregion
